config/routes.rb
Rails.application.routes.draw do
  get 'spa/new'
  get 'spa/create'
  resources :students
  resources :sections
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :sections
    
    def self.search(search)
      if search
        Course.where("name LIKE ?", "%#{search}%")
      else
        Course.all
      end
    end
    
    validates :name, presence: true
    validates :number, presence: true, format: {:with => /^\d+\.?\d*$/, :message => "only allows numbers", :multiline => true}
    validates :credit_hours, presence: true, format: {:with => /^\d+\.?\d*$/, :message => "only allows numbers", :multiline => true}
    validates_associated :sections
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_and_belongs_to_many :students
  
  def name_with_number
    "#{semester} #{number}"
  end
  
    def self.search(search)
      if search
        Section.where("name LIKE ?", "%#{search}%")
      else
        Section.all
      end
    end

  validates :semester, presence: true, length: { maximum: 6, message: "only SPRING, FALL, or SUMMER are valid"}
  validates :department, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :section
  
    validates :first_name, presence: true
    validates :last_name, presence: true
    
    def self.search(search)
      if search
        Student.where("name LIKE ?", "%#{search}%")
      else
        Student.all
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :department, :number, :credit_hours)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    @courses = Course.all
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:semester, :number, :course_id, :room_number)
    end
end

app/controllers/spa_controller.rb
class SpaController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  
  # GET /students/search
  def students_search
    @students = Students.search(params[:search].split('=').last)
    respond_to :js
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @sections = Section.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @sections = Section.all
    @courses = Course.all
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :section_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/spa_helper.rb
module SpaHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :credit_hours %>
    <%= form.number_field :credit_hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<%= stylesheet_link_tag "courses" %>

<p id="notice"><%= notice %></p>

<h1 id="course-header">Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Number</th>
      <th>Credit hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.department %></td>
        <td><%= course.number %></td>
        <td><%= course.credit_hours %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Course', new_course_path, class: "new-course" %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @course.department %>
</p>

<p>
  <strong>Number:</strong>
  <%= @course.number %>
</p>

<p>
  <strong>Credit hours:</strong>
  <%= @course.credit_hours %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniversityApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
    <header class='clearfix'>
      <div class="left-nav">
        <ul>
          <li><%= link_to "Courses", courses_path %></li>
        </ul>
      </div>
      <div class="right-nav">
        <ul>
          <li><%= link_to "Sections", sections_path %></li>
        </ul>
      </div>
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    </header>
    <div class="content">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      <%= yield %>
    </div>
    </body>
</html>

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field course">
    <%= form.label :course %>
      <%= collection_select( :section, :course_id, Course.all, :id, :name, {}, {multiple: false}) %>
    </div>

  <div class="field">
    <%= form.label :room_number %>
    <%= form.number_field :room_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Semester</th>
      <th>Number</th>
      <th>Course</th>
      <th>Room number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.semester %></td>
        <td><%= section.number %></td>
        <td><%= section.course.name %></td>
        <td><%= section.room_number %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Number:</strong>
  <%= @section.number %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @section.room_number %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

app/views/spa/create.html.erb
<html>
<head>
<title>A very simple SPA in Vue and Axios</title>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>

<div id="Itemlist">
    <button v-on:click="doajax('courses')">courses</button>
    <button v-on:click="doajax('sections')">sections</button>
    <button v-on:click="doajax('students')">students</button>
    <ul>
    <div v-for="item in items">
        <li>{{item.name}}</li>
    </div>
    </ul>
</div>

<script type="text/javascript">
var ItemsVue = new Vue({
    el: '#Itemlist',
    data: { items: [] },
    methods: {
        doajax: function(which) {
            axios.get('http://910c6d80473d49a99c1edae8923871ab.vfs.cloud9.us-east-2.amazonaws.com/' + which + '.json')
                .then(response => { this.items = response.data })
                .catch(error => { console.log(error); });
        }
    }
});
</script>

</body>
</html>

app/views/spa/new.html.erb
<h1>Spa#new</h1>
<p>Find me in app/views/spa/new.html.erb</p>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
    
  <div class="field section">
    <%= form.label :section %>
      <%= form.grouped_collection_select :section_id, Course.order(:name), :sections, :name, :id, :name_with_number, include_blank: true%>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_students.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Student Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<%= form_tag students_path, :method => 'get', :id => "students_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="students"><%= render 'students' %></div>
<% end %>



<%= link_to 'New Student', new_student_path %>

app/views/students/index.js.erb
$("#students").html("<%= escape_javascript(render("students")) %>");

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @student.section %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>